spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springDemo
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  security:
    user:
      name: deshan
server:
  port: 8089
