server:
  port: 8065
  servlet:
    session:
      cookie:
        name: KSESSIONID
spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
security:
  oauth2:
    client:
      client-id: admin
      client-secret: adminpass
      user-authorization-uri: http://localhost:8093/oauth/authorize
      access-token-uri: http://localhost:8093/oauth/token
    resource:
      token-info-uri: http://localhost:8093/oauth/check_token